name: Print hello message - running add lable

on: 
  pull_request:
    type: created
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - run: gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-review"
        env: 
          GH_TOKEN: ${{GITHUB_TOKEN}}


          
