name: Print hello message

on: [push, issues]
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello @{{ github.actor }}! :wave:
            Thanks for your contribution to the project.
            We appreciate your effort and time.
            If you have any questions, feel free to ask!
  
